name: Semanticore

on:
  push:
    branches:
      - main
jobs:
  semanticore:
    runs-on: ubuntu-latest
    name: Semanticore
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.*'
      - name: Semanticore
        run: go run . -changelog-max-lines 100
        env:
          SEMANTICORE_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GOTOOLCHAIN: auto
